[phases.setup]
aptPkgs = ["libwayland-dev", "pkg-config", "libasound2-dev", "libudev-dev", "libffi-dev", "libffi"]

[phases.build]
commands = [
    "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
]